### ISSUE TITLE
Unable to open the database

### ISSUE THREAD

**Issue by vaygr** [robertranjan/kpcli#2]
Hi,

thanks for this tool! I'm having a couple of issues with database opening:

1. Can not open the database if the database doesn't have a key (only password protection)
2. Can not open the database if it's encrypted with Twofish

**Comment by robertranjan** [comment]
I don't think, we can update the tool to work without a `keyfile` as it [depends on another module](https://github.com/robertranjan/kpcli/blob/main/cmd/createdb.go#L102) that creates the db and that need both `keyfile` and password.

Thanks for the issue but I can't help, sorry,

**Comment by robertranjan** [comment]
As per this [code block](https://github.com/robertranjan/kpcli/blob/main/cmd/runner.go#L149), this tool will return nil and exit.

```
	if d.Options.Key == "" || d.Options.Database == "" {
		fmt.Printf("%v"+`   --keyfile and --database are required arguments.
	If you are trying, run below commands:
	1. kpcli createdb
	2. kpcli ls`+"%v\nHere is usage:\n%v", colorYellow, colorGreen, colorReset)
		cli.ShowAppHelpAndExit(app, 0)
		return nil
	}
```

**Comment by vaygr** [comment]
@robertranjan as per example on the main page at https://github.com/tobischo/gokeepasslib I see you can just use `gokeepasslib.NewPasswordCredentials()` without the key.

**Comment by robertranjan** [comment]
@vaygr, thanks for the pointer. 
Implemented this feature. Please verify.

**Comment by robertranjan** [comment]
```
bin/kpcli \
  --database ${KDBX_DATABASE} \
  --pass ${KDBX_PASSWORD} \
  --nokey \
  create

bin/kpcli \
  --database ${KDBX_DATABASE} \
  --pass ${KDBX_PASSWORD} \
  --nokey \
  ls
```

**Comment by vaygr** [comment]
Thanks! This line prevents `ls` from running:

https://github.com/robertranjan/kpcli/blob/main/cmd/runner.go#L154

But once I fix it, as I mentioned, there's another issue: it cannot decode Twofish-encrypted database, even though the underlying library supports it:

https://github.com/tobischo/gokeepasslib/blob/master/header.go#L71

Here's the error message I'm getting:

```
time="2024-04-18T06:57:48-07:00" level=error msg="failed to decode dbfile: db.kdbx err:gzip: invalid header" func="github.com/robertranjan/kpcli/cmd.(*db).Unlock" file="kpcli/cmd/ls.go:28"
failed to unlock dbfile: db.kdbx, err: gzip: invalid header
execution failed with err: gzip: invalid header
```

**Comment by vaygr** [comment]
Seems Twofish issue is related to the library. I opened https://github.com/tobischo/gokeepasslib/issues/109. So only the line in `ls` I mentioned above remains.

**Comment by vaygr** [comment]
On Twofish: seems I was looking at the wrong place. It seems it's not implemented: https://github.com/tobischo/gokeepasslib/tree/master/crypto

**Comment by robertranjan** [comment]
@vaygr there were some changes done, please reverify and update if there are any issues. we can close it otherwise.

**Comment by vaygr** [comment]
@robertranjan I see this line is still unchanged: https://github.com/robertranjan/kpcli/blob/main/cmd/cmd.go#L428 so the issue remains.

Also regarding Twofish: it was fixed in the upstream library, could you pull in **3.6.0** that contains the fix?

**Comment by robertranjan** [comment]
upgraded gokeepasslib version to 3.6.

**Comment by vaygr** [comment]
Thank you!
