### ISSUE TITLE
List command (and possibly others) doesn't return entries in subfolders

### ISSUE THREAD

**Issue by vaygr** [robertranjan/kpcli#5]
I have about 500 entries in my keepass database. Most of them are residing in subfolders.

When I tried `kpcli --database database.kdbx --nokey ls`, it returned only 167 entries.

Is there a way to recursively get the rest?

**Comment by robertranjan** [comment]
That should be possible. I'll take a look.

**Comment by robertranjan** [comment]
@vaygr , is this still a problem?

**Comment by vaygr** [comment]
@robertranjan yes

**Comment by robertranjan** [comment]
at this point, just looking at the root folder/group and sub folder/group only. 

[Line 47 of ls.go](https://github.com/robertranjan/kpcli/blob/main/cmd/ls.go#L47)

```
func (d *kdbx) FetchDBEntries() {
	for _, rootgp := range d.RawData.Content.Root.Groups {
		for _, grp := range rootgp.Groups {
			d.FetchGrpEntries(grp)
		}
		d.FetchGrpEntries(rootgp)
	}
}
```
we should look for a way to continuously read until we reach the end/leaves.

**Comment by robertranjan** [comment]
pr #7 should fix recursive listing issue

**Comment by vaygr** [comment]
Yep, this is excellent. Works now. Probably deserves a new tagged release. Thank you!
